name: magma-access-gateway
base: core20
version: '1.8.0'
summary: Snap for Magma Access Gateway
description: |-
  The Access Gateway (AGW) provides network services and policy enforcement. In an LTE network, 
  the AGW implements an evolved packet core (EPC), and a combination of an AAA and a PGW. It works 
  with existing, unmodified commercial radio hardware.
  For more information on Magma please visit the official website - https://magmacore.org/.
  
  **WARNING:** Installing this snap will affect your computer's networking configuration. 
  Make sure it is installed on designated hardware (personal computers are strongly discouraged).
  
  **System requirements:**
  
  Hardware (baremetal strongly recommended)

  - Processor: x86-64 dual-core processor (around 2GHz clock speed or faster)
  - Memory: 4GB RAM
  - Storage: 32GB or greater SSD
  
  Networking
  
  - At least two ethernet interfaces (SGi and S1)
  - Internet connectivity from SGi interface
  
  Operating System

  - Ubuntu 20.04 LTS

confinement: classic

environment:
  PYTHONPATH: "$SNAP/lib/python3.8/site-packages"

apps:
  install:
    command: bin/install-agw
  configure:
    command: bin/configure-agw
  post-install:
    command: bin/agw-postinstall

parts:
  magma-access-gateway:
    plugin: python
    source: python
    build-packages:
      - libsystemd-dev
      - pkg-config
