name: main-branch-pull-request-created
on:
  pull_request:
    branches:
      - 1.6

jobs:
  agw-lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: |
          set -eux
          cd python && tox -e lint

  agw-static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev
          set -eux
          cd python && tox -e static

  agw-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev
          set -eux
          cd python && tox -e unit

  build-snap:
    name: Build Magma AGW snap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
