name: main-branch-pull-request-created
on:
  pull_request:
    branches:
      - main

jobs:
  agw-lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          set -eux
          cd python && tox -e lint

  agw-static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev
          set -eux
          cd python && tox -e static

  agw-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev
          set -eux
          cd python && tox -e unit

  build-snap:
    name: Build Magma AGW snap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
