name: push-to-branch
on:
  push:
    branches:
      - "**"
      - "!main"
      - "!1.6"

jobs:
  agw-lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox==3.21.4
      - name: Run tests using tox
        run: |
          set -eux
          cd python && tox -e lint

  agw-static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox==3.21.4
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev=245.4-4ubuntu3.19
          set -eux
          cd python && tox -e static

  agw-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox==3.21.4
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev=245.4-4ubuntu3.19
          set -eux
          cd python && tox -e unit

  build-snap:
    name: Build Magma AGW snap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
