name: merge-to-main
on:
  push:
    branches:
      - main

jobs:
  agw-lint-report:
    name: Lint report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          set -eux
          cd python && tox -e lint

  agw-static-analysis:
    name: Static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev
          set -eux
          cd python && tox -e static

  agw-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          sudo apt update
          sudo apt install libsystemd-dev
          set -eux
          cd python && tox -e unit

  build-and-publish-snap:
    name: Build and publish Magma AGW snap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v3
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
