name: push-to-branch
on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  agw-lint-report:
    name: Lint report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          set -eux
          tox -e lint

  agw-static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          sudo apt install libsystemd-dev
          set -eux
          tox -e static

  agw-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: |
          sudo apt install libsystemd-dev
          set -eux
          tox -e unit

  build-and-publish-snap:
    name: Build and publish Magma AGW snap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch_name
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPSTORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ steps.get_branch_name.outputs.branch_name }}/edge
